### ISSUE TITLE
link to rendered report in README is broken?

### ISSUE THREAD

**Issue by bbolker** [kariljordan/carpentry-assessment-projects#15]
https://kariljordan.github.io/carpentry-community-assessment-projects/software-carpentry-projects/analysis-postworkshop.html

Seems that it should actually be

https://kariljordan.github.io/carpentry-assessment-projects/software-carpentry-projects/analysis-postworkshop.html

**Comment by kariljordan** [comment]
Thanks @bbolker! It's all fixed now.
